server:
  port: 8888
  shutdown: graceful # 开启优雅停机,默认IMMEDIATE是立即关机 https://juejin.im/post/5ec1d89de51d454ddf2367ab
spring:
  profiles:
    active: actuator, mysql, nginx, logging, oauth2, quartz, activiti
  application:
    name: main # 主模块 必须写横杠,不能写下划线
#  main:
#    allow-bean-definition-overriding: true

